name: Sync Cloudflare R2 Data to GitHub

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 4 * * *
  watch:
    types: [started]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Configure rclone for Cloudflare R2
      env:
        CONF_DIR: "~/.config/rclone"
        CONF_PATH: "~/.config/rclone/rclone.conf"
      run: |
        mkdir -p ${CONF_DIR}
        echo "[cloudflare_r2]" >> ${CONF_PATH}
        echo "type = s3" >> ${CONF_PATH}
        echo "provider = Cloudflare" >> ${CONF_PATH}
        echo "access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}" >> ${CONF_PATH}
        echo "secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}" >> ${CONF_PATH}
        echo "endpoint = ${{ secrets.R2_ENDPOINT }}" >> ${CONF_PATH}

    - name: Sync data from Cloudflare R2 to GitHub
      env:
        SYNC_DIR: "/home/runner/work/sync"
        WORKSPACE: ${{github.workspace}}
      run: |
        mkdir -p ${SYNC_DIR} && cd ${SYNC_DIR}

        rclone sync "cloudflare_r2:${{ secrets.R2_BUCKET_NAME }}" ./ --progress

        cd ${WORKSPACE}

        git checkout --orphan=images
        git rm -rf .

        cp ${SYNC_DIR}/* -r ${WORKSPACE}

    - name: Commit and push changes to GitHub
      working-directory: ${{github.workspace}}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Sync Cloudflare R2 Data"
        git push -u origin images -f
