name: Sync Cloudflare R2 to GitHub

on:
  push:
    branches:
      - master  # 触发同步的分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Configure rclone for Cloudflare R2
      run: |
        mkdir -p ~/.config/rclone
        echo "[cloudflare_r2]" > ~/.config/rclone/rclone.conf
        echo "type = s3" >> ~/.config/rclone/rclone.conf
        echo "provider = Cloudflare" >> ~/.config/rclone/rclone.conf
        echo "access_key_id = ${{ secrets.R2_ACCESS_KEY_ID }}" >> ~/.config/rclone/rclone.conf
        echo "secret_access_key = ${{ secrets.R2_SECRET_ACCESS_KEY }}" >> ~/.config/rclone/rclone.conf
        echo "region = us-east-1" >> ~/.config/rclone/rclone.conf
        echo "endpoint = ${{ secrets.R2_ENDPOINT }}" >> ~/.config/rclone/rclone.conf

    - name: Sync data from Cloudflare R2 to GitHub
      working-directory: ${{github.workspace}}
      run: |
        cd /home/runner/work && mkdir -p sync && cd sync

        rclone sync "cloudflare_r2:${{ secrets.R2_BUCKET_NAME }}" ./ --progress

        cd ${{github.workspace}}

        git checkout --orphan=images
        git rm -rf .

        cp /home/runner/work/sync/* -r ${{github.workspace}}

    - name: Commit and push changes to GitHub
      working-directory: ${{github.workspace}}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Sync Cloudflare R2 data"
        git push -u origin images -f
